server:
  port: 8081
  address: 127.0.0.1
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
demo:
  springboot:
    customerType: SuperVIP
    customerCode: HuTao
    customerName: 七濑小胡桃
    customerPhone: 10086

logging:
  level:
    root: info
  file:
    name: e:/Code/test_springboot/log/log.log
#  pattern:
#    console: %logger[100] %msg%n
#    file: %logger[100] %msg%n
spring:
  datasource:
    username: hzero
    password: Q4E%kizUy2#m
    url: jdbc:mysql://192.168.56.201:3306/springboot_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    mode: HTML5

mybatis:
  type-aliases-package: com.example.test_springboot.domain.entity
  mapper-locations: classpath:mybatis/*.xml

